version: '3.8'
services:
    minio:
        image: minio/minio:RELEASE.2025-09-07T16-13-09Z
        container_name: minio
        environment:
            - MINIO_ROOT_USER=minioadmin
            - MINIO_ROOT_PASSWORD=minioadmin
            - MINIO_DEFAULT_BUCKETS=default
        volumes:
          - ./persistent/minio:/data
        networks:
            - frontend
        restart: unless-stopped
        command: 
          - server
          - "/data"

    # util service to create bucket
    minio-mb:
        image: minio/minio:RELEASE.2025-09-07T16-13-09Z
        container_name: minio-mb
        depends_on:
            - minio
        restart: on-failure
        entrypoint: >
            /bin/sh -c "
            sleep 5;
            /usr/bin/mc alias set dockerminio http://minio:9000 minioadmin minioadmin;
            /usr/bin/mc mb dockerminio/default;
            exit 0;
            "
        networks:
            - frontend




    lightdash:
        platform: linux/amd64
        # as of 2025/10/17
        # image: lightdash/lightdash:0.2091.1
        image: lightdash/lightdash
        container_name: lightdash
        depends_on:
            - db
            - minio
        environment:
            - PGHOST=${PGHOST:-db}
            - PGPORT=${PGPORT:-5432}
            - PGUSER=${PGUSER:-postgres}
            - PGPASSWORD=${PGPASSWORD}
            - PGDATABASE=${PGDATABASE:-postgres}
            - SECURE_COOKIES=${SECURE_COOKIES:-false}
            - TRUST_PROXY=${TRUST_PROXY:-false}
            - LIGHTDASH_SECRET=${LIGHTDASH_SECRET}
            - PORT=${PORT:-8080}
            - LIGHTDASH_LOG_LEVEL=warn
            - LIGHTDASH_INSTALL_ID=${LIGHTDASH_INSTALL_ID}
            - LIGHTDASH_INSTALL_TYPE=${LIGHTDASH_INSTALL_TYPE:-docker_image}
            - LIGHTDASH_LICENSE_KEY=${LIGHTDASH_LICENSE_KEY}
            - AUTH_DISABLE_PASSWORD_AUTHENTICATION=${AUTH_DISABLE_PASSWORD_AUTHENTICATION}
            - AUTH_ENABLE_GROUP_SYNC=${AUTH_ENABLE_GROUP_SYNC}
            - AUTH_GOOGLE_ENABLED=${AUTH_GOOGLE_ENABLED}
            - AUTH_GOOGLE_OAUTH2_CLIENT_ID=${AUTH_GOOGLE_OAUTH2_CLIENT_ID}
            - AUTH_GOOGLE_OAUTH2_CLIENT_SECRET=${AUTH_GOOGLE_OAUTH2_CLIENT_SECRET}
            - SITE_URL=${SITE_URL}
            - EMAIL_SMTP_HOST=${EMAIL_SMTP_HOST}
            - EMAIL_SMTP_PORT=${EMAIL_SMTP_PORT}
            - EMAIL_SMTP_SECURE=${EMAIL_SMTP_SECURE}
            - EMAIL_SMTP_USE_AUTH=${EMAIL_SMTP_USE_AUTH}
            - EMAIL_SMTP_USER=${EMAIL_SMTP_USER}
            - EMAIL_SMTP_PASSWORD=${EMAIL_SMTP_PASSWORD}
            - EMAIL_SMTP_ALLOW_INVALID_CERT=${EMAIL_SMTP_ALLOW_INVALID_CERT}
            - EMAIL_SMTP_SENDER_NAME=${EMAIL_SMTP_SENDER_NAME}
            - EMAIL_SMTP_SENDER_EMAIL=${EMAIL_SMTP_SENDER_EMAIL}
            - ALLOW_MULTIPLE_ORGS=${ALLOW_MULTIPLE_ORGS:-false}
            - LIGHTDASH_QUERY_MAX_LIMIT=${LIGHTDASH_QUERY_MAX_LIMIT}
            - LIGHTDASH_MAX_PAYLOAD=${LIGHTDASH_MAX_PAYLOAD:-5mb}
            - HEADLESS_BROWSER_HOST=headless-browser
            - HEADLESS_BROWSER_PORT=3000
            - USE_SECURE_BROWSER=${USE_SECURE_BROWSER}
            - RUDDERSTACK_WRITE_KEY=${RUDDERSTACK_WRITE_KEY}
            - RUDDERSTACK_DATA_PLANE_URL=${RUDDERSTACK_DATA_PLANE_URL}
            - SCHEDULER_ENABLED=true
            - GROUPS_ENABLED=${GROUPS_ENABLED:-false}
            - POSTHOG_PROJECT_API_KEY=${POSTHOG_PROJECT_API_KEY}
            - POSTHOG_FE_API_HOST=${POSTHOG_FE_API_HOST}
            - POSTHOG_BE_API_HOST=${POSTHOG_BE_API_HOST}
            - OPENAI_API_KEY=${OPENAI_API_KEY}
            - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
            - AI_COPILOT_ENABLED=${AI_COPILOT_ENABLED}
            - GOOGLE_DRIVE_API_KEY=${GOOGLE_DRIVE_API_KEY}
            - SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET}
            - SLACK_CLIENT_ID=${SLACK_CLIENT_ID}
            - SLACK_CLIENT_SECRET=${SLACK_CLIENT_SECRET}
            - SLACK_STATE_SECRET=${SLACK_STATE_SECRET}
            - GITHUB_PRIVATE_KEY=${GITHUB_PRIVATE_KEY}
            - GITHUB_APP_ID=${GITHUB_APP_ID}
            - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
            - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
            - GITHUB_APP_NAME=${GITHUB_APP_NAME}
            - GITHUB_REDIRECT_DOMAIN=${GITHUB_REDIRECT_DOMAIN}
            - S3_ENDPOINT=${S3_ENDPOINT:-http://minio:9000}
            - S3_REGION=${S3_REGION:-us-east-1}
            - S3_BUCKET=${S3_BUCKET:-default}
            - S3_ACCESS_KEY=${S3_ACCESS_KEY:-minioadmin}
            - S3_SECRET_KEY=${S3_SECRET_KEY:-minioadmin}
            - S3_FORCE_PATH_STYLE=${S3_FORCE_PATH_STYLE:-true}
            - S3_EXPIRATION_TIME=${S3_EXPIRATION_TIME}
            - RESULTS_S3_REGION=${RESULTS_S3_REGION:-${RESULTS_CACHE_S3_REGION}}
            - RESULTS_S3_BUCKET=${RESULTS_S3_BUCKET:-${RESULTS_CACHE_S3_BUCKET}}
            - RESULTS_S3_SECRET_KEY=${RESULTS_S3_SECRET_KEY:-${RESULTS_CACHE_S3_SECRET_KEY}}
            - RESULTS_S3_ACCESS_KEY=${RESULTS_S3_ACCESS_KEY:-${RESULTS_CACHE_S3_ACCESS_KEY}}
        env_file: ./.env
        networks:
            - frontend
        restart: unless-stopped

    db:
        image: postgres:15.4
        restart: unless-stopped
        container_name: db
        environment:
            POSTGRES_PASSWORD: ${PGPASSWORD}
            POSTGRES_USER: ${PGUSER:-postgres}
            POSTGRES_DB: ${PGDATABASE:-postgres}
        volumes:
            - ./persistent/db:/var/lib/postgresql/data
            # - db-data:/var/lib/postgresql/data
        env_file: ./.env
        networks:
            - frontend

    headless-browser:
        image: ghcr.io/browserless/chromium:v2.24.3
        restart: unless-stopped
        networks:
         - frontend

    watchtower:  
        image: containrrr/watchtower  
        container_name: watchtower  
        volumes:  
            - /var/run/docker.sock:/var/run/docker.sock  
        environment:  
            - WATCHTOWER_CLEANUP=true  
            - WATCHTOWER_SCHEDULE=0 0 3 * * * 
            - TZ=Asia/Ho_Chi_Minh 
        networks:  
            - frontend  
        restart: unless-stopped
        command: lightdash

networks:
    frontend:
        external: true
